In [1]:
import torch 
from torch import nn
from torch.utils.data import Dataset,DataLoader
import torch.nn.functional as F

# Section 1 : vocabulary and (train/val split)

In [2]:
# Imagine this is out entire dataset. 
raw_text = 'The cat is hungry I went to the store But it was closed So I went to a different store'

![](section_1.png)

split the dataset into train and validation sets

In [3]:
ratio = 0.66 # arbitrary ratio
split_index = int(len(raw_text) * ratio)
train_raw_text = raw_text[:split_index]
val_raw_text = raw_text[split_index:]


print(f"Train raw text: {train_raw_text}")

print("="*100)

print(f"Val raw text: {val_raw_text}")


Train raw text: The cat is hungry I went to the store But it was closed 
Val raw text: So I went to a different store


Corpus vocabulary


We will make an assumption that each word is a unique token.<br>
This is a simplification and not true in the real world.<br>
In practice, we would use a more sophisticated tokenization method.


In [4]:
vocab = list(sorted(set(raw_text.split(' '))))

print("unique words in the corpus:")
print("-"*50)
for i in vocab:
    print(i)

print("="*50)
vocab_size = len(vocab)
print(f'vocab_size: {vocab_size}') # You can think of as number of unique words in the corpus. 

unique words in the corpus:
--------------------------------------------------
But
I
So
The
a
cat
closed
different
hungry
is
it
store
the
to
was
went
vocab_size: 16


Note: (The) is different from (the)

In [5]:
tokens_to_ids = {token: id for id, token in enumerate(vocab)}
print("Mapping of tokens to ids:")
tokens_to_ids

Mapping of tokens to ids:


{'But': 0,
 'I': 1,
 'So': 2,
 'The': 3,
 'a': 4,
 'cat': 5,
 'closed': 6,
 'different': 7,
 'hungry': 8,
 'is': 9,
 'it': 10,
 'store': 11,
 'the': 12,
 'to': 13,
 'was': 14,
 'went': 15}

In [6]:
ids_to_tokens = {id: token for id, token in enumerate(vocab)}
print("Mapping of ids to tokens:")
ids_to_tokens

Mapping of ids to tokens:


{0: 'But',
 1: 'I',
 2: 'So',
 3: 'The',
 4: 'a',
 5: 'cat',
 6: 'closed',
 7: 'different',
 8: 'hungry',
 9: 'is',
 10: 'it',
 11: 'store',
 12: 'the',
 13: 'to',
 14: 'was',
 15: 'went'}

In [7]:
def encode(text):
    return [tokens_to_ids[token] for token in text.strip().split(' ')]

def decode(ids):
    return ' '.join([ids_to_tokens[id] for id in ids])

In [8]:
encode(raw_text)

[3, 5, 9, 8, 1, 15, 13, 12, 11, 0, 10, 14, 6, 2, 1, 15, 13, 4, 7, 11]

In [9]:
encode("The cat is hungry")

[3, 5, 9, 8]

In [10]:
decode([3,5,9,8])

'The cat is hungry'

# Section 2 : Creating  dataset and dataloader 

### Dataset & DataLoader Config

In [11]:
# X aka input 
max_len = 4  # length of the green bracket
stride = 3  # jump of the green bracket

# y aka output 
# The red bracket length and jump are the same as the green bracket,
# but it is shifted by one token to the right.

Note : max_len and stride are hyper-parameters and can be tuned.

![](section_2.png)

### Dataset 

In [12]:
class Data(Dataset):
    def __init__(self,raw_text,max_len=max_len,stride=stride):
        self.token_ids = encode(raw_text)
        self.X = []
        self.y = []
        for i in range(0,len(self.token_ids)-max_len,stride):
            input = self.token_ids[i:i+max_len]
            output = self.token_ids[i+1:i+max_len+1]
            self.X.append(torch.tensor(input))
            self.y.append(torch.tensor(output))
            
    def __len__(self):
        return len(self.X)
    
    def __getitem__(self,idx):
        return self.X[idx],self.y[idx]
    

In [13]:
train_ds = Data(train_raw_text)
train_ds[0]

(tensor([3, 5, 9, 8]), tensor([5, 9, 8, 1]))

In [14]:
val_ds = Data(val_raw_text)
val_ds[0]

(tensor([ 2,  1, 15, 13]), tensor([ 1, 15, 13,  4]))

### DataLoader

In [15]:
train_dl = DataLoader(train_ds,batch_size=1,shuffle=False,drop_last=False,num_workers=0)
val_dl   = DataLoader(val_ds,batch_size=1,shuffle=False,drop_last=True,num_workers=0)

In [16]:
# for i,(x,y) in enumerate(train_dl):
#   print(f'Batch Number: {i+1}')
#   print(f'x :{x}')
#   print(f'y :{y}')
#   print('--'*20)

In [17]:
# for i,(x,y) in enumerate(val_dl):
#   print(f'Batch Number: {i+1}')
#   print(f'x :{x}')
#   print(f'y :{y}')
#   print('--'*20)

# Section 3 : Token Embedding and Positional Encoding 

Taking single batch, and we know that the batch size is 1. <br>
so we are taking a single example from the dataset. 

In [18]:
for x,y in train_dl:
  print(x)
  print(y)
  break

tensor([[3, 5, 9, 8]])
tensor([[5, 9, 8, 1]])


In [19]:
B = 1  # batch size 
d_in = 4  # embedding dimension  [input dimension]

In [20]:
torch.manual_seed(1)

# Embedding 
token_emb = nn.Embedding(vocab_size,d_in)
token_embedding = token_emb(x)
print('Token Embeddings:')
print(token_embedding)


Token Embeddings:
tensor([[[-0.2223,  1.6871,  0.2284,  0.4676],
         [ 0.8657,  0.2444, -0.6629,  0.8073],
         [ 0.1991,  0.0457,  0.1530, -0.4757],
         [ 1.8793, -0.0721,  0.1578, -0.7735]]], grad_fn=<EmbeddingBackward0>)


In [21]:
context_window = 4 # [max length of the input sequence the model can handle]
num_tokens = 4 # this can not be greater than context window


torch.manual_seed(1)

# Positional embedding
pos_emb = nn.Embedding(context_window,d_in)
positional_embedding = pos_emb(torch.arange(num_tokens))
print('Positional Embeddings:')
print('--'*20)
print(positional_embedding)
print('--'*20)
print(positional_embedding.shape)

Positional Embeddings:
----------------------------------------
tensor([[-1.5256, -0.7502, -0.6540, -1.6095],
        [-0.1002, -0.6092, -0.9798, -1.6091],
        [-0.7121,  0.3037, -0.7773, -0.2515],
        [-0.2223,  1.6871,  0.2284,  0.4676]], grad_fn=<EmbeddingBackward0>)
----------------------------------------
torch.Size([4, 4])


In [22]:
# Token embedding + token embedding 
tok_pos_emb = token_embedding + positional_embedding
print('Token Embedding + Positional Embedding')
print('--'*20)
print(tok_pos_emb)
print('--'*20)
print(tok_pos_emb.shape)

Token Embedding + Positional Embedding
----------------------------------------
tensor([[[-1.7479,  0.9369, -0.4256, -1.1418],
         [ 0.7655, -0.3648, -1.6427, -0.8018],
         [-0.5131,  0.3494, -0.6244, -0.7271],
         [ 1.6571,  1.6150,  0.3862, -0.3058]]], grad_fn=<AddBackward0>)
----------------------------------------
torch.Size([1, 4, 4])


# Section 4 : Pre Transformer Block Dropout 

In [23]:
dropout = 0.25 # notice that we are not using it, but we are still initializing it(to see how it works)


torch.manual_seed(2)

pre_trans_dp = nn.Dropout(dropout)
pre_transformer_dp_result = pre_trans_dp(tok_pos_emb)
pre_transformer_dp_result

tensor([[[-0.0000,  1.2492, -0.5674, -1.5225],
         [ 0.0000, -0.4864, -2.1902, -1.0691],
         [-0.6841,  0.4659, -0.8325, -0.9695],
         [ 2.2094,  0.0000,  0.5149, -0.4078]]], grad_fn=<MulBackward0>)

# Section5 : Transformer Block 

### Layer Normalization 

In [24]:
layernorm1 = nn.LayerNorm(d_in)
print(layernorm1.weight)
print(layernorm1.bias)
layernorm1 = layernorm1(pre_transformer_dp_result)
print(layernorm1)
print('--'*20)
print(layernorm1.shape)


Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)
tensor([[[ 0.2096,  1.4551, -0.3562, -1.3084],
         [ 1.1463,  0.5509, -1.5349, -0.1624],
         [-0.3144,  1.7046, -0.5748, -0.8154],
         [ 1.6361, -0.5812, -0.0645, -0.9905]]],
       grad_fn=<NativeLayerNormBackward0>)
----------------------------------------
torch.Size([1, 4, 4])


### Multi-Head Attention 

weights initialization 

In [25]:
d_out = 4

W_q = nn.Parameter(torch.tensor([
    [-0.5, 0.2, 0.7, -0.9],
    [0.1, -0.3, 0.8, 0.4],
    [-0.7, 0.6, -0.2, 0.9],
    [0.3, -0.8, 0.5, -0.1]
]))


W_k = nn.Parameter(torch.tensor([
    [0.3, -0.5, 0.2, 0.7],
    [-0.4, 0.1, -0.6, -0.2],
    [0.8, -0.3, 0.5, -0.7],
    [-0.1, 0.6, -0.9, 0.4]
]))

W_v = nn.Parameter(torch.tensor([
    [0.2, -0.8, 0.3, 0.5],
    [-0.7, 0.4, -0.1, -0.6],
    [0.9, -0.2, 0.7, -0.3],
    [-0.5, 0.1, -0.4, 0.8]
]))



print('W_q')
print(W_q.data.shape)
print('---'*20)

print('W_k')
print(W_k.data.shape)
print('---'*20)

print('W_v')
print(W_v.data.shape)
print('---'*20)

W_q
torch.Size([4, 4])
------------------------------------------------------------
W_k
torch.Size([4, 4])
------------------------------------------------------------
W_v
torch.Size([4, 4])
------------------------------------------------------------


Q,K,V

In [26]:
Q = layernorm1 @ W_q
K = layernorm1 @ W_k
V = layernorm1 @ W_v

print('Q')
print(Q.data)
print(Q.data.shape)
print('---'*20)

print('K')
print(K.data)
print(K.data.shape)
print('---'*20)

print('V')
print(V.data)
print(V.data.shape)
print('---'*20)


Q
tensor([[[-0.1025,  0.4384,  0.7278,  0.2037],
         [ 0.5076, -0.7271,  1.4690, -2.1765],
         [ 0.4854, -0.2668,  0.8509,  0.5290],
         [-1.1282,  1.2553,  0.1980, -1.6640]]])
torch.Size([1, 4, 4])
------------------------------------------------------------
K
tensor([[[-0.6733, -0.6375,  0.1684, -0.4184],
         [-1.0882, -0.1550, -0.7226,  1.7017],
         [-1.1545,  0.0108, -0.6392, -0.4848],
         [ 0.7708, -1.4511,  1.5352,  0.9105]]])
torch.Size([1, 4, 4])
------------------------------------------------------------
V
tensor([[[-0.6430,  0.3548,  0.1914, -1.7081],
         [-1.4566, -0.4060, -0.7207,  0.5732],
         [-1.3657,  0.9668, -0.3410, -1.6598],
         [ 1.1713, -1.6276,  0.9000,  0.3938]]])
torch.Size([1, 4, 4])
------------------------------------------------------------


### splitting Q,K,V into multiple heads 

In [27]:
num_heads = 2               # this is a hyper-parameter and can be tuned. 
head_dim = d_out//num_heads
print(head_dim)

2


In [28]:
Q_multi_head  = Q.view(B,num_tokens,num_heads,head_dim).transpose(1,2)
K_multi_head  = K.view(B,num_tokens,num_heads,head_dim).transpose(1,2)
V_multi_head  = V.view(B,num_tokens,num_heads,head_dim).transpose(1,2)


print('Q_multi_head')
print(Q_multi_head.data)
print(Q_multi_head.data.shape)

print('---'*20)

print('K_multi_head')
print(K_multi_head.data)
print(K_multi_head.data.shape)


print('---'*20)

print('V_multi_head')
print(V_multi_head.data)
print(V_multi_head.data.shape)

Q_multi_head
tensor([[[[-0.1025,  0.4384],
          [ 0.5076, -0.7271],
          [ 0.4854, -0.2668],
          [-1.1282,  1.2553]],

         [[ 0.7278,  0.2037],
          [ 1.4690, -2.1765],
          [ 0.8509,  0.5290],
          [ 0.1980, -1.6640]]]])
torch.Size([1, 2, 4, 2])
------------------------------------------------------------
K_multi_head
tensor([[[[-0.6733, -0.6375],
          [-1.0882, -0.1550],
          [-1.1545,  0.0108],
          [ 0.7708, -1.4511]],

         [[ 0.1684, -0.4184],
          [-0.7226,  1.7017],
          [-0.6392, -0.4848],
          [ 1.5352,  0.9105]]]])
torch.Size([1, 2, 4, 2])
------------------------------------------------------------
V_multi_head
tensor([[[[-0.6430,  0.3548],
          [-1.4566, -0.4060],
          [-1.3657,  0.9668],
          [ 1.1713, -1.6276]],

         [[ 0.1914, -1.7081],
          [-0.7207,  0.5732],
          [-0.3410, -1.6598],
          [ 0.9000,  0.3938]]]])
torch.Size([1, 2, 4, 2])


### Attention Score 

In [29]:
K_multi_head_transpose = K_multi_head.transpose(2,3)

print('K_multi_head_transpose')
print(K_multi_head_transpose.data)
print(K_multi_head_transpose.data.shape)

K_multi_head_transpose
tensor([[[[-0.6733, -1.0882, -1.1545,  0.7708],
          [-0.6375, -0.1550,  0.0108, -1.4511]],

         [[ 0.1684, -0.7226, -0.6392,  1.5352],
          [-0.4184,  1.7017, -0.4848,  0.9105]]]])
torch.Size([1, 2, 2, 4])


In [30]:
attn_score = Q_multi_head @ K_multi_head_transpose
print(attn_score)
print(attn_score.shape)

tensor([[[[-0.2105,  0.0435,  0.1231, -0.7152],
          [ 0.1217, -0.4397, -0.5940,  1.4464],
          [-0.1567, -0.4868, -0.5633,  0.7614],
          [-0.0406,  1.0331,  1.3161, -2.6912]],

         [[ 0.0373, -0.1792, -0.5639,  1.3027],
          [ 1.1579, -4.7654,  0.1161,  0.2734],
          [-0.0780,  0.2853, -0.8003,  1.7879],
          [ 0.7295, -2.9747,  0.6801, -1.2111]]]],
       grad_fn=<UnsafeViewBackward0>)
torch.Size([1, 2, 4, 4])


### mask

In [31]:
mask = torch.triu(torch.ones(num_tokens,num_tokens),diagonal=1)
print(mask)
print(mask.bool()) 

tensor([[0., 1., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])
tensor([[False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True],
        [False, False, False, False]])


In [32]:
attn_score = attn_score.masked_fill(mask.bool()[:num_tokens,:num_tokens],-torch.inf)
print(attn_score)

tensor([[[[-0.2105,    -inf,    -inf,    -inf],
          [ 0.1217, -0.4397,    -inf,    -inf],
          [-0.1567, -0.4868, -0.5633,    -inf],
          [-0.0406,  1.0331,  1.3161, -2.6912]],

         [[ 0.0373,    -inf,    -inf,    -inf],
          [ 1.1579, -4.7654,    -inf,    -inf],
          [-0.0780,  0.2853, -0.8003,    -inf],
          [ 0.7295, -2.9747,  0.6801, -1.2111]]]],
       grad_fn=<MaskedFillBackward0>)


In [33]:
attn_weight = torch.softmax(attn_score/K_multi_head.shape[-1]**0.5,dim=-1)
print(attn_weight)

tensor([[[[1.0000, 0.0000, 0.0000, 0.0000],
          [0.5980, 0.4020, 0.0000, 0.0000],
          [0.3934, 0.3115, 0.2951, 0.0000],
          [0.1695, 0.3621, 0.4424, 0.0260]],

         [[1.0000, 0.0000, 0.0000, 0.0000],
          [0.9851, 0.0149, 0.0000, 0.0000],
          [0.3457, 0.4469, 0.2074, 0.0000],
          [0.4363, 0.0318, 0.4213, 0.1106]]]], grad_fn=<SoftmaxBackward0>)


In [34]:
torch.manual_seed(3)

attn_dropout = nn.Dropout(dropout)

attn_weight = attn_dropout(attn_weight)
print(attn_weight)

tensor([[[[1.3333, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.5361, 0.0000, 0.0000],
          [0.5245, 0.0000, 0.3935, 0.0000],
          [0.2260, 0.4828, 0.0000, 0.0347]],

         [[1.3333, 0.0000, 0.0000, 0.0000],
          [1.3134, 0.0199, 0.0000, 0.0000],
          [0.4609, 0.5959, 0.2766, 0.0000],
          [0.5817, 0.0424, 0.0000, 0.1475]]]], grad_fn=<MulBackward0>)


In [35]:
con_vector = attn_weight @ V_multi_head
print(con_vector)
print(con_vector.shape)

tensor([[[[-0.8573,  0.4730],
          [-0.7808, -0.2176],
          [-0.8746,  0.5665],
          [-0.8080, -0.1723]],

         [[ 0.2552, -2.2775],
          [ 0.2370, -2.2321],
          [-0.4355, -0.9047],
          [ 0.2135, -0.9113]]]], grad_fn=<UnsafeViewBackward0>)
torch.Size([1, 2, 4, 2])


In [36]:
conv_vector = con_vector.transpose(1,2).contiguous().view(B,num_tokens,d_out)
conv_vector

tensor([[[-0.8573,  0.4730,  0.2552, -2.2775],
         [-0.7808, -0.2176,  0.2370, -2.2321],
         [-0.8746,  0.5665, -0.4355, -0.9047],
         [-0.8080, -0.1723,  0.2135, -0.9113]]], grad_fn=<ViewBackward0>)

In [37]:
# projection 

out_proj = nn.Parameter(torch.tensor([
    [0.5, -0.3, 0.4, 0.2],
    [-0.6, 0.4, -0.2, -0.5], 
    [0.3, -0.7, 0.6, -0.4],
    [-0.2, 0.5, -0.4, 0.3]
]))

print(out_proj.data)
print(out_proj.data.shape)
print('--'*20)

tensor([[ 0.5000, -0.3000,  0.4000,  0.2000],
        [-0.6000,  0.4000, -0.2000, -0.5000],
        [ 0.3000, -0.7000,  0.6000, -0.4000],
        [-0.2000,  0.5000, -0.4000,  0.3000]])
torch.Size([4, 4])
----------------------------------------


In [38]:
out_proj_result = conv_vector @ out_proj.data
print(out_proj_result)
print(out_proj_result.shape)


tensor([[[-0.1804, -0.8710,  0.6266, -1.1933],
         [ 0.2577, -1.1348,  0.7662, -0.8118],
         [-0.7269,  0.3415, -0.3626, -0.5554],
         [-0.0543, -0.4316,  0.2039, -0.4343]]], grad_fn=<UnsafeViewBackward0>)
torch.Size([1, 4, 4])


# Dropout1 

In [39]:
torch.manual_seed(3)
dropout1 = nn.Dropout(dropout)
after_dropout_1 = dropout1(out_proj_result)
print(after_dropout_1)
print(after_dropout_1.shape)

tensor([[[-0.2405, -1.1613,  0.0000, -1.5911],
         [ 0.0000, -1.5130,  1.0217, -1.0824],
         [-0.9692,  0.0000, -0.4834, -0.7405],
         [-0.0724, -0.5755,  0.0000, -0.5790]]], grad_fn=<MulBackward0>)
torch.Size([1, 4, 4])


# Skip Connection 

In [40]:
skip_connection = after_dropout_1 + pre_transformer_dp_result
print(skip_connection)
print(skip_connection.shape)

tensor([[[-0.2405,  0.0878, -0.5674, -3.1136],
         [ 0.0000, -1.9994, -1.1686, -2.1514],
         [-1.6534,  0.4659, -1.3159, -1.7100],
         [ 2.1370, -0.5755,  0.5149, -0.9868]]], grad_fn=<AddBackward0>)
torch.Size([1, 4, 4])


# LayerNorm 2

In [41]:
layernorm2 = nn.LayerNorm(after_dropout_1.shape[-1])
print(layernorm2.weight)
print(layernorm2.bias)
layernorm2_result = layernorm2(after_dropout_1)

print(layernorm2_result)
print(layernorm2_result.shape)

Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)
tensor([[[ 0.7791, -0.6339,  1.1482, -1.2934],
         [ 0.3992, -1.1360,  1.4358, -0.6990],
         [-1.1686,  1.5222,  0.1800, -0.5336],
         [ 0.8623, -0.9891,  1.1287, -1.0019]]],
       grad_fn=<NativeLayerNormBackward0>)
torch.Size([1, 4, 4])


# FC

In [42]:
fc1_weight = nn.Parameter(torch.tensor([
    [0.5, -0.3, 0.4, 0.2, 0.1, -0.2, 0.3, -0.1],
    [-0.6, 0.4, -0.2, -0.5, 0.2, 0.3, -0.4, 0.5],
    [0.3, -0.7, 0.6, -0.4, -0.3, 0.4, 0.2, -0.6],
    [-0.2, 0.5, -0.4, 0.3, 0.4, -0.5, 0.1, 0.2]
]))

fc1_bias  = nn.Parameter(torch.tensor([0.1, -0.2, 0.3, -0.1, 0.2, -0.3, 0.4, -0.2]))


print(fc1_weight.data.shape)
print('--'*20)

print(fc1_bias.data.shape)
print('--'*20)

fc1_result = (layernorm2_result @ fc1_weight.data) + fc1_bias.data
print(fc1_result.data)
print(fc1_result.shape)

torch.Size([4, 8])
----------------------------------------
torch.Size([8])
----------------------------------------
tensor([[[ 1.4730, -2.1377,  1.9447, -0.4745, -0.7107,  0.4600,  0.9876,
          -1.5424],
         [ 1.5517, -2.1287,  1.8280, -0.2362, -0.6976,  0.2032,  1.1914,
          -1.8092],
         [-1.2369,  0.3666, -0.1504, -1.3269,  0.1201,  0.7292, -0.5768,
           0.4632],
         [ 1.6635, -2.1453,  1.9207, -0.1851, -0.6510,  0.1833,  1.1798,
          -1.6583]]])
torch.Size([1, 4, 8])


In [43]:
gelu = nn.GELU()
gelu_result = gelu(fc1_result)
gelu_result

tensor([[[ 1.3694, -0.0348,  1.8943, -0.1507, -0.1696,  0.3115,  0.8279,
          -0.0948],
         [ 1.4581, -0.0354,  1.7662, -0.0961, -0.1693,  0.1180,  1.0523,
          -0.0637],
         [-0.1337,  0.2358, -0.0662, -0.1224,  0.0658,  0.5593, -0.1627,
           0.3142],
         [ 1.5835, -0.0342,  1.8681, -0.0789, -0.1676,  0.1050,  1.0394,
          -0.0806]]], grad_fn=<GeluBackward0>)

In [44]:
fc2_weight = nn.Parameter(torch.tensor([
    [0.5, -0.6, 0.3, -0.2],
    [-0.3, 0.4, -0.7, 0.5], 
    [0.4, -0.2, 0.6, -0.4],
    [0.2, -0.5, -0.4, 0.3],
    [0.1, 0.2, -0.3, 0.4],
    [-0.2, 0.3, 0.4, -0.5],
    [0.3, -0.4, 0.2, 0.1],
    [-0.1, 0.5, -0.6, 0.2]
]))


print(fc2_weight.data.shape)
print('--'*20)

fc2_bias  = nn.Parameter(torch.tensor([0.1, -0.2, 0.3, -0.1]))
print(fc2_bias.data.shape)
print('--'*20)


torch.Size([8, 4])
----------------------------------------
torch.Size([4])
----------------------------------------


In [45]:
fc2_result = (gelu_result @ fc2_weight.data) + fc2_bias.data
print(fc2_result)
print(fc2_result.shape)

tensor([[[ 1.7013, -1.6581,  2.3300, -1.3539],
         [ 1.8085, -1.8455,  2.2070, -1.1788],
         [-0.2740,  0.4521,  0.0870, -0.1724],
         [ 1.9156, -1.9561,  2.3000, -1.2365]]], grad_fn=<AddBackward0>)
torch.Size([1, 4, 4])


# Dropout 2 

In [46]:
torch.manual_seed(2)

dropout2 = nn.Dropout(dropout)
dropout2_result = dropout2(fc2_result)
dropout2_result

tensor([[[ 0.0000, -2.2108,  3.1066, -1.8053],
         [ 0.0000, -2.4606,  2.9427, -1.5718],
         [-0.3654,  0.6028,  0.1160, -0.2298],
         [ 2.5542, -0.0000,  3.0667, -1.6486]]], grad_fn=<MulBackward0>)

End of Transformer block 

##  skip connection 2

In [47]:
skip_connection_2 = skip_connection + dropout2_result
print(skip_connection_2)


tensor([[[-0.2405, -2.1230,  2.5392, -4.9188],
         [ 0.0000, -4.4600,  1.7741, -3.7232],
         [-2.0187,  1.0687, -1.1999, -1.9399],
         [ 4.6912, -0.5755,  3.5816, -2.6354]]], grad_fn=<AddBackward0>)


# Post Transformer Block LayerNorm

In [48]:
post_transformer_LN = nn.LayerNorm(d_out)
print(post_transformer_LN.weight)
print(post_transformer_LN.bias)
post_transformer_LN_result = post_transformer_LN(skip_connection_2)
print(post_transformer_LN_result)

Parameter containing:
tensor([1., 1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0.], requires_grad=True)
tensor([[[ 0.3476, -0.3446,  1.3697, -1.3727],
         [ 0.6210, -1.1075,  1.3085, -0.8220],
         [-0.7978,  1.6744, -0.1421, -0.7346],
         [ 1.1466, -0.6162,  0.7752, -1.3056]]],
       grad_fn=<NativeLayerNormBackward0>)


# Head_out 

In [49]:
head_out = nn.Parameter(torch.tensor([
    [0.5, -0.3, 0.4, 0.2, 0.1, -0.2, 0.3, -0.1, 0.4, -0.5, 0.2, 0.3, -0.2, 0.1, -0.3, 0.4],
    [-0.6, 0.4, -0.2, -0.5, 0.2, 0.3, -0.4, 0.5, -0.3, 0.2, -0.5, 0.4, 0.3, -0.2, 0.5, -0.4],
    [0.3, -0.7, 0.6, -0.4, -0.3, 0.4, 0.2, -0.6, 0.5, -0.2, 0.4, -0.3, 0.2, -0.5, 0.3, -0.1],
    [-0.2, 0.5, -0.4, 0.3, 0.4, -0.5, 0.1, 0.2, -0.4, 0.3, -0.2, 0.5, -0.3, 0.4, -0.5, 0.2]
]))

print(head_out.shape)


torch.Size([4, 16])


In [50]:
head_out_logits = post_transformer_LN_result @ head_out
head_out_logits.shape

torch.Size([1, 4, 16])

In [51]:
head_out_logits 

tensor([[[ 1.0660, -1.8873,  1.5789, -0.7179, -0.9942,  1.0613,  0.3788,
          -1.3034,  1.4764, -0.9285,  1.0643, -1.1308,  0.5129, -1.1303,
           0.8207, -0.1346],
         [ 1.5319, -1.9562,  1.5838, -0.0921, -0.8807,  0.4779,  0.8088,
          -1.5653,  1.5637, -1.0403,  1.3657, -1.0603,  0.0519, -0.6994,
           0.0635,  0.3961],
         [-1.2993,  0.6413, -0.4454, -1.1603,  0.0039,  0.9723, -1.0110,
           0.8553, -0.5986,  0.5418, -0.9067,  0.1058,  0.8538, -0.6375,
           1.4012, -1.1216],
         [ 1.4367, -1.7859,  1.5693, -0.1644, -0.7634,  0.5487,  0.6149,
          -1.1490,  1.5534, -1.2433,  1.1086, -0.7879,  0.1326, -0.6720,
           0.2333,  0.3665]]], grad_fn=<UnsafeViewBackward0>)

# Softmax 

In [52]:
# we won't be using the following head_out_prob to calculate the loss, since we can use cross entropy loss 
# calculating softmax is for demonstration purpose only  

head_out_prob = F.softmax(head_out_logits,dim=-1)
print(head_out_prob)
print(head_out_prob.shape)

tensor([[[0.1095, 0.0057, 0.1829, 0.0184, 0.0140, 0.1090, 0.0551, 0.0102,
          0.1651, 0.0149, 0.1093, 0.0122, 0.0630, 0.0122, 0.0857, 0.0330],
         [0.1622, 0.0050, 0.1708, 0.0320, 0.0145, 0.0565, 0.0787, 0.0073,
          0.1674, 0.0124, 0.1373, 0.0121, 0.0369, 0.0174, 0.0373, 0.0521],
         [0.0133, 0.0925, 0.0312, 0.0153, 0.0489, 0.1287, 0.0177, 0.1145,
          0.0268, 0.0837, 0.0197, 0.0541, 0.1144, 0.0257, 0.1977, 0.0159],
         [0.1544, 0.0062, 0.1763, 0.0311, 0.0171, 0.0635, 0.0679, 0.0116,
          0.1735, 0.0106, 0.1112, 0.0167, 0.0419, 0.0187, 0.0463, 0.0529]]],
       grad_fn=<SoftmaxBackward0>)
torch.Size([1, 4, 16])


In [53]:
head_out_prob.shape

torch.Size([1, 4, 16])

In [54]:
head_out_prob.argmax(dim=1)

tensor([[1, 2, 0, 1, 2, 2, 1, 2, 3, 2, 1, 2, 2, 2, 2, 3]])

In [55]:
head_out_prob.argmax(dim=1).shape

torch.Size([1, 16])

# Loss 

In [56]:
loss_fn = nn.CrossEntropyLoss()
loss_fn(head_out_logits.squeeze(0),y.squeeze(0))

tensor(3.8299, grad_fn=<NllLossBackward0>)

# The End of the forward pass 